tap "caskroom/cask"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/core"
brew "fzf"
brew "jq"
brew "libgit2"
brew "neovim"
brew "python"
brew "socat"
brew "tmux"
brew "zplug", args: ["with-zsh"]
brew "zsh"
cask "font-source-code-pro-for-powerline"
